#!/bin/bash

set +e
set +x

source /etc/sysconfig/postfix || true

/etc/postfix/system/config_postfix || true
/etc/postfix/system/update_chroot || true
/etc/postfix/system/update_postmaps || true
(/usr/sbin/postfix start || true) &
/etc/postfix/system/wait_qmgr 60 || true
/etc/postfix/system/cond_slp register || true

set -e
set -x
