#!/bin/bash

# Check for configuration existance
if [ ! -d /config ]; then
    echo "You have not mapped /config"
fi
if [ ! -e /config/generate ]; then
    echo "You have not created /config/generate"
fi

# Copy servers from configuration
echo "Generating server configurations..."
mkdir /etc/nginx/servers
cp /config/generate /etc/nginx/servers/generate
pushd /etc/nginx/servers
./generate
popd
rm generate

if [ -d /config/certs ]; then
    echo "Copying SSL certificates..."
    cp -Rv /config/certs /etc/nginx/certs
fi

# Check syntax
/usr/sbin/nginx -t
if [ $? -ne 0 ]; then
    echo "Nginx syntax check fail"
    exit 1
fi

# Run Nginx
/usr/sbin/nginx

# Wait for /run/nginx.pid to appear and copy it.
while [ ! -e /run/nginx.pid ]; do
  echo "Waiting for /run/nginx.pid to appear..."
  sleep 1
done
cp /run/nginx.pid /run/watch/nginx

